name             'omnibus_serverspec'
maintainer       'HiganWorks LLC.'
maintainer_email 'sawanoboriyu@higanworks.com'
license          'apache2'
description      'Install omnibus_serverspec'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.1'
supports         'rhel'
supports         'centos'
supports         'debian'
supports         'ubunth'
